version: '3.8'

services:
  chat-service:
    build: ./chat-service
    ports:
      - "8001:8080"
    environment:
      - RAG_SERVICE_URL=http://rag-service:8000
      - LLM_SERVICE_URL=http://llm-service:8000
    # depends_on:
    #   - rag-service
    #   - llm-service

  # rag-service:
  #   build: ./rag-service
  #   ports:
  #     - "8002:8000"

  # llm-service:
  #   build: ./llm-service
  #   ports:
  #     - "8003:8000"